name: SW-SWI-SRM-MapServices


services:
  redis:
    image: redis:7.4-alpine
    restart: always
    labels:
      - "traefik.enable=false"
    command: >
      sh -c '
      mkdir -p /usr/local/etc/redis &&
      echo "user default on >$$REDIS_PASSWORD ~* +@all" > /usr/local/etc/redis/users.acl &&
      exec redis-server --save 60 1 --loglevel warning --aclfile /usr/local/etc/redis/users.acl
      '
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      REDIS_PASSWORD: ${MAPSERVICES_REDIS_PWD}
    networks:
      - internal


  mapproxy-server:
    image: ghcr.io/unis-svalbard-weather-information/swi-mapproxy:trixie-p3.13-mp6.0.1-0.0.12
    volumes:
      - map-data:/mapproxy/data
      - map-metadata:/mapproxy/metadata
      - tiles-cache:/mapproxy/mbtiles/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mapproxy-server.rule=Host(`${SWI_MAPPROXY_HOST?Variable not set}`)"
      - "traefik.http.routers.mapproxy-server.entrypoints=websecure"
      - "traefik.http.routers.mapproxy-server.tls=true"
      - "traefik.http.services.mapproxy-server.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

      # CORS middleware
      - "traefik.http.middlewares.mapproxycors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.mapproxycors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.mapproxycors.headers.accesscontrolalloworiginlist=${CORS_ALLOWED_ORIGINS?Variable not set}"
      - "traefik.http.middlewares.mapproxycors.headers.accesscontrolallowcredentials=true"

      # Additional headers middleware
      - "traefik.http.middlewares.mapproxyheaders.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.middlewares.mapproxyheaders.headers.customrequestheaders.X-Forwarded-Host=${SWI_MAPPROXY_HOST?Variable not set}"
      - "traefik.http.middlewares.mapproxyheaders.headers.customresponseheaders.Cache-Control=public, max-age=60, s-maxage=60"

      # Apply middlewares
      - "traefik.http.routers.mapproxy-server.middlewares=mapproxycors,mapproxyheaders"

      # Sticky Session
      - "traefik.http.services.mapproxy-server.loadbalancer.sticky=true"

    healthcheck:
      test: ["CMD-SHELL", "/mapproxy/health-check.sh"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 3
    restart: always
    environment:
      - MAPPROXY_REDIS_HOST=redis
      - MAPPROXY_REDIS_PORT=6379
      - MAPPROXY_REDIS_USERNAME=default
      - MAPPROXY_REDIS_PASSWORD=${MAPSERVICES_REDIS_PWD}
    depends_on:
      - redis
    networks:
      - proxy
      - internal


  CRON_seaice_cache:
    image: ghcr.io/unis-svalbard-weather-information/swi-mapcache-seaice:0.0.10
    labels:
      - "traefik.enable=false"
    volumes:
      - map-data:/swi/export
      - map-metadata:/swi/metadata
    environment:
      - DOCKER_CRON=1
      - SWI_SEAICE_MONITORING_ENDPOINT=${SWI_SEAICE_MONITORING_ENDPOINT}
    depends_on:
      - mapproxy-server
    networks:
      - internal


  CRON_avalanche_cache:
    image: ghcr.io/unis-svalbard-weather-information/swi-avalanche-caching:0.0.3
    labels:
      - "traefik.enable=false"
    volumes:
      - map-data:/swi/data
      - map-metadata:/swi/metadata
      - aval-raster-cache:/swi/static
    environment:
      - DOCKER_CRON=1
      - SWI_AVALANCHE_MONITORING_ENDPOINT=${SWI_AVALANCHE_MONITORING_ENDPOINT}
    depends_on:
      - mapproxy-server
    networks:
      - internal

volumes:
  tiles-cache:

  map-data:

  map-metadata:

  aval-raster-cache:
    driver: local

  redis_data:
    driver: local


networks:
  proxy:
    external: true
  internal:
    driver: bridge